spring.application.name=Musicboxd

# PostgreSQL Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/musicboxddb
spring.datasource.username=postgres
spring.datasource.password=sua_senha_aqui
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA/Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# Application Configuration
spring.jmx.enabled=false
server.port=8080